version: "3.1"

services:
  pg:
    image: "dbzioum/pg"
    build:
      context: scripts/pg
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/pg/pg_setup.sh:/docker-entrypoint-initdb.d/pg_setup.sh
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"

  mysql:
    image: "mysql:8"
    restart: "always"
    command: --default-authentication-plugin=mysql_native_password --binlog-row-metadata=FULL
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "test"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#--source-verify-checksum=OFF
#--binlog-checksum=NONE

