version: "3.1"

services:
  pg:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "postgres"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
