version: "3.1"

services:
  pg:
    image: "dbzioum/pg"
    build:
      context: scripts/pg
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/pg/pg_setup.sh:/docker-entrypoint-initdb.d/pg_setup.sh
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "test"

  mysql:
    image: "mysql:8"
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./scripts/mysql/mysql_setup.sh:/docker-entrypoint-initdb.d/mysql_setup.sh
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "password"
#--source-verify-checksum=OFF
#--binlog-checksum=NONE

